version: "3.4"

services:
  shopping.api:
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"
    depends_on:
      - shopping.db
    ports:
      - "8000:80"
  shopping.client:
    container_name: shoppingClient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ShoppingAPIUrl=http://shoppingapi"
    ports:
      - "8001:80"
    depends_on:
      - shopping.db
      - shopping.api
  shopping.db:
    container_name: shoppingdb
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
